### ISSUE TITLE
Include of non modular header inside framework module.

### ISSUE THREAD

**Issue by ashiqsulaimanbaryons** [jancassio/SweetHMAC#4]
I am getting two errors as soon as i import SweetHMAC to the project. Check out the image.
<img width="1472" alt="fullscreen_23_08_16__12_08_pm" src="https://cloud.githubusercontent.com/assets/20036490/17882526/8acf5d0e-692a-11e6-8e79-cdcc9c028efb.png">

**Comment by jancassio** [comment]
Hi @ashiqsulaimanbaryons ,

Could you describe how you added SweetHMAC in your project please?

Seems you are using Xcode 8 beta, isn't? I'm not sure if this is an Xcode issue. 

Also, I'll try to use it on Xcode 8 with instructions I provided in README.md file to ensure the instructions works on both Xcode versions.

Thank you for reporting.

**Comment by ashiqsulaimanbaryons** [comment]
Hi @jancassio, I am using Xcode 7.3. I added SweetHMAC via Cocoapods.

**Comment by jancassio** [comment]
Thanks for details @ashiqsulaimanbaryons , actually there is an [issue opened](https://github.com/jancassio/SweetHMAC/issues/3) for Cocoapods compatibility.

You can use SweetHMAC project [integrated](https://github.com/jancassio/SweetHMAC#integrated-project) in your own project.

Let me know if this works for you.

Thank you.

**Comment by ashiqsulaimanbaryons** [comment]
it worked when i directly included the code to my project. It would be great if you could create a cocoapod for the same. Thank you.
